{% set name = "unidep" %}
{% set version = "0.25.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/unidep-{{ version }}.tar.gz
  sha256: e50140186bea76d37f40f778b491a900fdc2fa357c5f6519ce296e712387c513

build:
  noarch: python
  entry_points:
    - unidep = unidep:main
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - setuptools >=42
    - wheel
    - pip
  run:
    - python >=3.7
    - ruamel.yaml
    - typing-extensions

test:
  imports:
    - unidep
  commands:
    - pip check
    - unidep --help
  requires:
    - pip

about:
  summary: Unified Conda and Pip requirements management.
  home: https://adaptive.readthedocs.io/
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - basnijholt
