{% set name = "unidep" %}
{% set version = "0.45.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/unidep-{{ version }}.tar.gz
  sha256: ad871f2b6e2d3a4681416fa1e4b681997f6f99e6929ad9cdd913c7f6075fbbab

build:
  noarch: python
  entry_points:
    - unidep = unidep:_cli.main
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - setuptools >=42
    - wheel
    - pip
  run:
    - python >=3.7
    - ruamel.yaml
    - typing-extensions
    - packaging
    - tomli
    - conda-package-handling  # optional requirement on PyPI
    - conda-lock  # optional requirement on PyPI
    - rich-argparse  # optional requirement on PyPI
    - pip-tools  # optional requirement on PyPI

test:
  imports:
    - unidep
  commands:
    - pip check
    - unidep --help
  requires:
    - pip

about:
  summary: Unified Conda and Pip requirements management.
  home: https://github.com/basnijholt/unidep/
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - basnijholt
