{% set name = "unidep" %}
{% set version = "0.63.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/unidep-{{ version }}.tar.gz
  sha256: b370a7a6a93bbbc0f085b5d801bd78c3dc24e388315763e496b93ce277a13525

build:
  noarch: python
  entry_points:
    - unidep = unidep:_cli.main
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - setuptools >=42
    - wheel
    - pip
  run:
    - python >=3.7
    - ruamel.yaml
    - typing-extensions
    - packaging
    - tomli

test:
  imports:
    - unidep
  commands:
    - pip check
    - unidep --help
  requires:
    - pip

about:
  summary: Unified Conda and Pip requirements management.
  home: https://github.com/basnijholt/unidep/
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - basnijholt
